tclcmd = { ...
'vsimulink low_pass_flter -t 1ns -voptargs=+acc  -f parameter_low_pass_flter.cfg  -socket 53721;', ...
'add wave low_pass_flter/*;', ...
};
vsim('tclstart',tclcmd,'vsimdir','C:\modeltech64_2020.4\win64')
